version: '3.2'
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            PYTHONDONTWRITEBYTECODE: 1
            FLASK_DEBUG: 1
        volumes:
            - .:/usr/src/app
            - ~/.currency-api-key.txt:/root/.currency-api-key.txt:ro
            - ~/.apilayer-api-key.txt:/root/.apilayer-api-key.txt:ro
